version: "3"
services:
    web: 
        image: nginx:latest
        restart: always
        volumes:
            - ./public:/var/www/html
            - ./conf.d:/etc/nginx/conf.d
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/data:/var/www/certbot
        ports:
            - 80:80
            - 443:443

    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/certbot --email oscarrafaelcampos@gmail.com --agree-tos --no-eff-email -d oscarrafael.pt -d www.oscarrafael.pt -d winpegasus.pt -d www.winpegasus.pt -d api.winpegasus.pt -d www.api.winpegasus.pt --expand
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data:/var/www/certbot
